/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hp_verifyimagination_verify_layout_funtion_NDKTestActivity */

#ifndef _Included_com_example_hp_verifyimagination_verify_layout_funtion_NDKTestActivity
#define _Included_com_example_hp_verifyimagination_verify_layout_funtion_NDKTestActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hp_verifyimagination_verify_layout_funtion_NDKTestActivity
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hp_verifyimagination_verify_layout_funtion_NDKTestActivity_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
